export default [
    {
        id:1,
        img:"../img/line.jpg" ,
        name:"kfc",
        spa:"Finger licking good" ,
        paragraph:"kkc",
        location:"Online",
        open:0 ,
    } , 
    { 
        id:2,
        img:"../img/weather.jpg" ,
        name:"Basketball" ,
        spa:"seeseh" ,
        paragraph:"yeah you like basketball i love it too",
        location:"Online",
        open:1 ,
    } ,
    {
        id:3,
        img:"../img/data.jpg" ,
        name:"Ngawang" ,
        spa:"Goodmorning korea" ,
        paragraph:"Annyeongesehyo i am ngawang a react developer",
        location:"Online",
        open:1 ,
    } , 
    {
        id:4,
        img:"../img/simon.jpg" ,
        name:"adidas" ,
        spa:"konnichiwa adidas" ,
        paragraph:"everything you need to know about adidas is here",
        location:"Online",
        open:1 ,
    },
    {
        id:5,
        img:"../img/security.jpg" ,
        name:"adidas" ,
        spa:"konnichiwa adidas" ,
        paragraph:"everything you need to know about adidas is here",
        location:"Online",
        open:1 ,
    },
    {
        id:6,
        img:"../img/drumkit.jpg" ,
        name:"adidas" ,
        spa:"konnichiwa adidas" ,
        paragraph:"everything you need to know about adidas is here",
        location:"Online",
        open:1 ,
    },
    {
        id:7,
        img:"../img/notes.jpg" ,
        name:"adidas" ,
        spa:"konnichiwa adidas" ,
        paragraph:"everything you need to know about adidas is here",
        location:"Online",
        open:1 ,
    },
    
    ]